
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
    - os: osx
      osx_image: xcode7.3
      language: cpp
      env: OPENSSL_ROOT_DIR=/usr/local/opt/openssl

cenv:
  global:
    - STEEM_VERSION=0.12.2

install: ./install.sh
before_script:
  - git clone https://github.com/steemit/steem.git
  - cd steem
  - git checkout v${STEEM_VERSION}
  - git submodule update --init --recursive
script:
  - cd steem
  - cmake .
  - make
