
os: osx
osx_image: xcode7.3
language: cpp
env:
  global:
    - OPENSSL_ROOT_DIR=/usr/local/opt/openssl
    - STEEM_VERSION=0.12.2

install:
  - brew update
  - brew upgrade cmake git autoconf automake libtool openssl
  - brew install qt5 python3
  # Downgrade boost to 1.58.0
  - brew unlink boost
  - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/1fa330ce7a067406ff05392dead86cccdc0794bd/Formula/boost.rb
  # Fix for "shell_session_update: command not found"
  - rvm get head
before_script:
  - git clone https://github.com/steemit/steem.git
  - cd ${TRAVIS_BUILD_DIR}/steem
  - git checkout v${STEEM_VERSION}
  - git submodule update --init --recursive
script:
  - cd ${TRAVIS_BUILD_DIR}/steem
  - cmake .
  - make
