matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3
env:
  - STEEM_VERSION=0.12.2
install: ./install.sh
before_script:
  - git clone https://github.com/steemit/steem.git
  - cd steem
  - git checkout v${STEEM_VERSION}
  - git submodule update --init --recursive
script:
  - cd steem
  - cmake .
  - make